### ISSUE TITLE
Support for IPython Audio 

### ISSUE THREAD

**Issue by Nelson-Gon** [posit-dev/py-shinywidgets#126]
* shinywidgets version: 0.2.4
* Python version: 3.10.13 
* Operating System: macOS 14.1.2 

### Description

I was trying to `insert_ui` for an `Audio` `IPython` widget by doing something like 

```
from IPython.display import display, Audio
ui.insert_ui(ui.tags.html(display(Audio(audio_file, **kwargs))))
```

My expectation was that this would recognize the generated IPython HTML and render it. It neither rendered not did it throw any error. I have played with `output_widget` and `register_widget` but it seems there is no audio support (or at least not one I am aware of) in ipywidgets. The end goal would be to have something like `streamlit`'s `audio` UI but with autoplay, a feature they still [lack](https://github.com/streamlit/streamlit/issues/2446)

Thanks,
NelsonGon

**Comment by cpsievert** [comment]
The `Audio` class doesn't inherit from the `ipywidgets`'s `Widget` class, so it won't be compatible with `{shinywidgets}`, but since it has a `_repr_html_` method, you can render it this way (this requires the development version of [`{htmltools}`](https://github.com/posit-dev/py-htmltools#installation)):

```python
from IPython.display import Audio

from shiny import App, render, ui

app_ui = ui.page_fluid(
    ui.output_ui("my_audio"),
)

def server(input, output, session):

    @render.ui
    def my_audio():
        return Audio("http://www.nch.com.au/acm/8k16bitpcm.wav")

app = App(app_ui, server)

```

**Comment by cpsievert** [comment]
Or if using the new shiny express mode, this just becomes:

```
from IPython.display import Audio

import shiny
import shiny.express

Audio("http://www.nch.com.au/acm/8k16bitpcm.wav")
```
