### ISSUE TITLE
Altair Facetchart rendering issue

### ISSUE THREAD

**Issue by dreamtori** [posit-dev/py-shinywidgets#142]
* shinywidgets version: 0.3.1
* Python version: 3.10.13
* Operating System: Windows

### Description

Hi team,

When we generate a facet chart, an error occurs while rendering the altair facet chart.

error message
Facetchart object has no attribute 'width'

I'd really appreciate your help. many thanks!

### What I Did
minimal example
```
from shiny.express import input, ui
from shinywidgets import render_altair

ui.input_selectize("var", "Select variable", choices=["bill_length_mm", "body_mass_g"])


@render_altair
def hist():
    import altair as alt
    from palmerpenguins import load_penguins

    df = load_penguins()
    return (
        alt.Chart(df)
        .mark_bar()
        .encode(x=alt.X(f"{input.var()}:Q", bin=True), y="count()")
    ).facet(column='species:N')

```

**Comment by cpsievert** [comment]
Thanks! I was quite surprised to learn that [vega doesn't support specifying height/width](https://github.com/vega/vega-lite/pull/6672) on a `FacetChart`, so the sizing will be awkward/non-responsive, but `@render_altair` won't error on it anymore.
