### ISSUE TITLE
Import render_plotly error

### ISSUE THREAD

**Issue by hessakh** [posit-dev/py-shinywidgets#145]
* shinywidgets version: 0.2.4
* Python version:  3.10.10
* Operating System: MAC OS 13.4

I get the following error when I try to import render_plotly from shiny widgets:

`from shinywidgets import render_plotly`

I get the error:

ImportError: cannot import name 'render_plotly' from 'shinywidgets'

Any help would be great, thanks!

**Comment by cpsievert** [comment]
You need to update to a more recent version of shinywidgets: `pip install -U shinywidgets`
